// Copyright_Team_AriAri


#include "Game/QGameModeVillage.h"

#include "QVillageGameState.h"
#include "Blueprint/WidgetBlueprintLibrary.h"
#include "Player/QPlayerState.h"
#include "UObject/ConstructorHelpers.h"
#include "GodCall.h"
#include "Kismet/GameplayStatics.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"

// ì •ì (static) ë³€ìˆ˜ ì •ì˜
int32 AQGameModeVillage::PlayerIDCount;
int32 AQGameModeVillage::NPCIDCount;
int32 AQGameModeVillage::EvidenceIDCount;
int32 AQGameModeVillage::ConversationIDCount;

AQGameModeVillage::AQGameModeVillage()
{
	static ConstructorHelpers::FClassFinder<APawn> PlayerClassRef(TEXT("/Game/Blueprints/Character/BP_QLaywer.BP_QLaywer_C"));
	if (PlayerClassRef.Class) {	// ThirdPersonClassRef.Classê°€ nullì´ ì•„ë‹ˆë¼ë©´
		DefaultPawnClass = PlayerClassRef.Class;
	}
	static ConstructorHelpers::FClassFinder<APlayerController> PlayerControllerRef(TEXT("/Game/Blueprints/Player/BP_QPlayerController.BP_QPlayerController_C"));
	if (PlayerControllerRef.Class)
	{
		PlayerControllerClass = PlayerControllerRef.Class;
	}
	GameStateClass = AQVillageGameState::StaticClass();
	PlayerStateClass = AQPlayerState::StaticClass();
	
	// ì •ì (static) ë³€ìˆ˜ëŠ” í´ë˜ìŠ¤ ì°¨ì›ì—ì„œ ê´€ë¦¬ë˜ë¯€ë¡œ, ìƒì„±ìì—ì„œ ê°’ì„ ì„¤ì •
	PlayerIDCount = PlayerIDInit;
	NPCIDCount = NPCIDInit;
	EvidenceIDCount = EvidenceIDInit;
	ConversationIDCount = ConversationIDInit;
}

void AQGameModeVillage::PostInitializeComponents()
{
	Super::PostInitializeComponents();

	UE_LOG(LogTemp, Log, TEXT("ğŸ“Œ PostInitializeComponents() ì‹¤í–‰ë¨!"));
	/*UE_LOG(LogTemp, Log, TEXT("QGameModeVillage::PostInitializeComponents() - í”„ë¡¬í”„íŠ¸ ë¯¸ë¦¬ ì¤€ë¹„ ì‹œì‘"));

	GeneratePromptsBeforeNextGame();*/
}

void AQGameModeVillage::BeginPlay()
{
	Super::BeginPlay();

	UE_LOG(LogTemp, Log, TEXT("AAIGameModeTest::BeginPlay() ì‹¤í–‰ë¨"));

	UWorld* World = GetWorld();
	if (!World)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ BeginPlay - World is nullptr!"));
		return;
	}

	// ê¸°ì¡´ GodActor ì°¾ê¸°
	TArray<AActor*> FoundActors;
	UGameplayStatics::GetAllActorsWithTag(World, TEXT("GodActor"), FoundActors);

	if (FoundActors.Num() == 0 || !FoundActors[0])
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ BeginPlay - GodActorë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŒ!"));
		return;
	}

	AActor* GodActor = FoundActors[0];
	UGodCall* GodCall = GodActor->FindComponentByClass<UGodCall>();

	if (!GodCall)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ BeginPlay - GodCallì„ ì°¾ì„ ìˆ˜ ì—†ìŒ!"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("âœ… BeginPlay - í”„ë¡¬í”„íŠ¸ ìƒì„± ì™„ë£Œ í›„ ê²Œì„ ì§„í–‰"));
}

void AQGameModeVillage::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	Super::EndPlay(EndPlayReason);
	UE_LOG(LogTemp, Log, TEXT("QGameModeVillage::EndPlay() - í”„ë¡¬í”„íŠ¸ ì‚­ì œ ë° ì¬ìƒì„± ì˜ˆì•½"));

	// ê²Œì„ ì¢…ë£Œ ì‹œ í”„ë¡¬í”„íŠ¸ ì‚­ì œ í›„ ë‹¤ì‹œ ìƒì„±
	if (EndPlayReason == EEndPlayReason::EndPlayInEditor)
    {
        UE_LOG(LogTemp, Log, TEXT("ğŸ”„ í”„ë¡¬í”„íŠ¸ ì‚­ì œ í›„ ë‹¤ì‹œ ìƒì„± ì‹œì‘"));
        GeneratePromptsBeforeNextGame();
    }
}

void AQGameModeVillage::GeneratePromptsBeforeNextGame()
{
	UWorld* World = GetWorld();
	if (!World)
	{
		UE_LOG(LogTemp, Error, TEXT("GeneratePromptsBeforeNextGame() - Worldê°€ NULL! í”„ë¡¬í”„íŠ¸ ìƒì„± ë¶ˆê°€"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("GeneratePromptsBeforeNextGame() - ê¸°ì¡´ í”„ë¡¬í”„íŠ¸ ì‚­ì œ í›„ ì¬ìƒì„± ì‹œì‘"));

	UE_LOG(LogTemp, Log, TEXT("GeneratePromptsBeforeNextGame() - PromptToDefendant.json ìƒì„± ì‹œì‘"));
	UGodFunction::GenerateDefendantPrompt(World, [World]()
		{
			UE_LOG(LogTemp, Log, TEXT("âœ… PromptToDefendant.json ìƒì„± ì™„ë£Œ! ë°°ì‹¬ì› ìƒì„± ì‹œì‘"));
			UGodFunction::GenerateJuryNPC(World, 1);
		});
}
