// Copyright_Team_AriAri

#include "ResidentComponent.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "HAL/PlatformFilemanager.h"
#include "JsonObjectConverter.h"
#include "GameFramework/PlayerState.h"
#include "GameFramework/PlayerController.h"

void UResidentComponent::BeginPlay()
{
    Super::BeginPlay();
    UE_LOG(LogTemp, Warning, TEXT("UResidentComponent::BeginPlay() ì‹¤í–‰ë¨ - NPC %s"), *NPCID);

    if (NPCID.IsEmpty())
        return;

    // ë§ˆì„ ì£¼ë¯¼ì˜ JSON íŒŒì¼ ê²½ë¡œ ì„¤ì •
    int32 ResidentIndex = FCString::Atoi(*NPCID) - 2003; // NPCID 2004 -> ResidentIndex 1

    if (ResidentIndex < 1 || ResidentIndex > 5)
        return;

    FString PromptFileName = FString::Printf(TEXT("PromptToResident%d.json"), ResidentIndex);
    PromptFilePath = FPaths::ConvertRelativePathToFull(FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("Prompt"), PromptFileName));

    UE_LOG(LogTemp, Log, TEXT("ResidentComponent - NPC %sëŠ” %së¥¼ ì‚¬ìš©í•©ë‹ˆë‹¤."), *NPCID, *PromptFilePath);

    // ë§ˆì„ ì£¼ë¯¼ ë°ì´í„° ë¡œë“œ
    if (!NPCID.IsEmpty())
        LoadPrompt();
}

void UResidentComponent::AskResidentQuestion(const FString& PlayerInput)
{
    if (PlayerInput.IsEmpty() || PlayerInput.Len() < 3)
    {
        UE_LOG(LogTemp, Warning, TEXT("Player input is too short or empty."));
        return;
    }

    UE_LOG(LogTemp, Log, TEXT("Player asked the Resident: %s"), *PlayerInput);

    // ğŸ¯ FOpenAIRequest êµ¬ì¡°ì²´ ì‚¬ìš©ìœ¼ë¡œ ë³€ê²½
    FOpenAIRequest AIRequest;
    AIRequest.Prompt = PlayerInput;
    AIRequest.SpeakerID = FCString::Atoi(*GetPlayerIDAsString());
    AIRequest.ListenerID = FCString::Atoi(*NPCID);
    AIRequest.ConversationType = EConversationType::P2N;
    AIRequest.MaxTokens = 150;

    StartConversation(AIRequest);
}

void UResidentComponent::StartConversation(const FOpenAIRequest& Request)
{
    if (PromptContent.IsEmpty())
    {
        UE_LOG(LogTemp, Error, TEXT("Prompt file is empty or failed to load for Resident: %d"), Request.ListenerID);
        return;
    }

    UE_LOG(LogTemp, Log, TEXT("Player started conversation with Resident %d: %s"), Request.ListenerID, *Request.Prompt);

    // ì²« ëŒ€í™” ì—¬ë¶€ í™•ì¸
    bool bIsFirstGreeting = !P2NDialogueHistory.Contains(FString::Printf(TEXT("%d"), Request.ListenerID)) ||
        P2NDialogueHistory[FString::Printf(TEXT("%d"), Request.ListenerID)].DialogueLines.Num() == 0;

    FOpenAIRequest AIRequest = Request;

    if (bIsFirstGreeting && Request.Prompt.IsEmpty())
    {
        // ì²« ëŒ€ì‚¬ ìƒì„±
        AIRequest.Prompt = FString::Printf(TEXT(
            "ì•„ë˜ ì„¤ì •ì„ ê°€ì§„ ì£¼ë¯¼ì´ í”Œë ˆì´ì–´ë¥¼ ì²˜ìŒ ë§Œë‚¬ì„ ë•Œ í•˜ëŠ” ì²« ì¸ì‚¬ë¥¼ ìƒì„±í•˜ì„¸ìš”.\n"
            "==== ì£¼ë¯¼ ì„¤ì • ====\n%s\n"
            "ì²« ì¸ì‚¬ëŠ” NPCì˜ ì„±ê²©ê³¼ ì„¤ì •ì„ ë°˜ì˜í•˜ì—¬ ìì—°ìŠ¤ëŸ½ê²Œ ì‘ì„±í•´ì•¼ í•©ë‹ˆë‹¤."),
            *PromptContent);
    }
    else
    {
        // ì¼ë°˜ì ì¸ P2N ëŒ€í™” ì²˜ë¦¬
        AIRequest.Prompt = FString::Printf(TEXT(
            "ì•„ë˜ ì„¤ì •ì„ ê°€ì§„ ì£¼ë¯¼ì´ í”Œë ˆì´ì–´ '%d'ì˜ ì§ˆë¬¸ì— ë‹µë³€í•©ë‹ˆë‹¤.\n"
            "==== ì£¼ë¯¼ ì„¤ì • ====\n%s\n"
            "==== í”Œë ˆì´ì–´ì˜ ì§ˆë¬¸ ====\n"
            "í”Œë ˆì´ì–´: \"%s\"\n"
            "ì£¼ë¯¼:"),
            Request.SpeakerID, *PromptContent, *Request.Prompt);
    }

    RequestOpenAIResponse(AIRequest, [this, Request](FOpenAIResponse AIResponse)
        {
            ResponseCache.Add(Request.Prompt, AIResponse.ResponseText);
            UE_LOG(LogTemp, Log, TEXT("OpenAI Response for Resident %d: %s"), Request.ListenerID, *AIResponse.ResponseText);

            // ì„œë²„ì— ì „ì²´ ì‘ë‹µ ì „ë‹¬ (FStringì´ ì•„ë‹Œ FOpenAIResponse í†µì§¸ë¡œ ì „ì†¡)
            SendNPCResponseToServer(AIResponse);

            // ëŒ€í™” ê¸°ë¡ ì €ì¥
            SaveP2NDialogue(Request.Prompt, AIResponse.ResponseText);
        });
}